language: ruby
default:
  prepare:
    exec:
      - yum install ruby19
      - echo 'export PATH=/opt/ruby19/bin:$PATH' >> ~/.bashrc
      - echo 'export LD_LIBRARY_PATH=/opt/ruby19/lib64' >> ~/.bashrc
      - gem install bundler
      - bundle install
  unit_test:
    exec:
      - bundle exec rake spec
